name: CI Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/*

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14.x' # You might need to adjust this value to your own version
    - name: Build
      id: build
      run: | 
        npm install
        npm run verify
        PLUGIN_NAME="$(node -p "require('./manifest.json').id")"
        mkdir "$PLUGIN_NAME"
        cp dist/main.js manifest.json styles.css "$PLUGIN_NAME"
        zip -r "$PLUGIN_NAME.zip" "$PLUGIN_NAME"
        ls
